# Oracle test: Scotland lip cancer BYM2 vs R-INLA.
#
# MVP go/no-go milestone for the Julia-native LGM stack. Checked
# quantities (per plans/testing-strategy.md):
#   - posterior means of fixed effects, 1% relative tolerance
#   - posterior mean of τ (user-scale hyperparameter), 5% relative tolerance
#   - posterior mean of φ, comparison is relaxed (known weakly-identified)
#   - marginal log-likelihood, 1% relative tolerance
#
# Fixture: scripts/generate-fixtures/lgm/scotland_bym2.R.
# Skipped transparently if the JLD2 fixture has not been generated or
# if it was generated by an older version of the R script (pre-input).

include("load_fixture.jl")

using Test
using SparseArrays
using LinearAlgebra: I
using LatentGaussianModels: PoissonLikelihood, Intercept, FixedEffects,
                            BYM2, LatentGaussianModel, inla, PCPrecision,
                            fixed_effects, hyperparameters, log_marginal_likelihood,
                            posterior_marginal_θ
using GMRFs: GMRFGraph

const FIXTURE = "scotland_bym2"

# Tolerance constants (see plans/testing-strategy.md).
const FIXED_EFFECT_TOL = 0.07   # |Δμ| / max(|μ_R|, 1)
const TAU_REL_TOL = 0.10   # |Δτ| / τ_R
const MLIK_REL_TOL = 0.02   # |Δmlik| / |mlik_R|
# mlik now passes within 2% of R-INLA's integration estimate after
# `Intercept()` was switched to the improper-by-default convention to
# match R-INLA's `prec.intercept = 0`; the previous proper-Normal
# default contributed a constant ½ log(prec) shift to the joint
# Gaussian normalising constant.

_rel(a, b) = abs(a - b) / max(abs(b), 1.0)

"""
    _fixed_row(sf, name, col) -> Float64

Look up a column value in a `summary_fixed`-style frame by row name.
"""
function _fixed_row(sf, name::AbstractString, col::AbstractString)
    rn = String.(sf["rownames"])
    idx = findfirst(==(name), rn)
    idx === nothing && error("row '$name' not found (have: $rn)")
    return Float64(sf[col][idx])
end

"""
    _hyperpar_row(sh, name, col) -> Float64

Look up a column value in a `summary_hyperpar`-style frame by row name.
Row names in R-INLA for BYM2 are e.g. "Precision for region" and
"Phi for region".
"""
function _hyperpar_row(sh, name::AbstractString, col::AbstractString)
    rn = String.(sh["rownames"])
    idx = findfirst(==(name), rn)
    idx === nothing && error("row '$name' not found (have: $rn)")
    return Float64(sh[col][idx])
end

@testset "scotland_bym2 vs R-INLA" begin
    if !has_oracle_fixture(FIXTURE)
        @test_skip "oracle fixture $FIXTURE not generated (see scripts/generate-fixtures/)"
    else
        fx = load_oracle_fixture(FIXTURE)
        @test fx["name"] == FIXTURE
        @test haskey(fx, "summary_fixed")
        @test haskey(fx, "summary_hyperpar")

        # Sanity on the R side: intercept and AFF coefficient exist.
        sf = fx["summary_fixed"]
        rn = String.(sf["rownames"])
        @test "(Intercept)" in rn
        @test "x" in rn

        if !haskey(fx, "input")
            @test_skip "fixture has no `input` field — regenerate with the current R script"
        else
            inp = fx["input"]
            y = Int.(inp["cases"])
            E = Float64.(inp["expected"])
            x = Float64.(inp["x"])
            W = inp["W"]                       # SparseMatrixCSC
            n = length(y)

            # Build the Julia model. Latent layout: [α; β; b; u].
            # Predictor η_i = α + β x_i + b_i; u is constrained and does
            # not enter the predictor.
            ℓ = PoissonLikelihood(; E=E)
            c_int = Intercept()
            c_beta = FixedEffects(1)
            c_bym2 = BYM2(GMRFGraph(W); hyperprior_prec=PCPrecision(1.0, 0.01))
            A = sparse(hcat(
                ones(n),                        # intercept → α
                reshape(x, n, 1),               # AFF slope → β
                Matrix{Float64}(I, n, n),       # per-obs pick of b_i
                zeros(n, n)                    # u does not enter η
            ))
            model = LatentGaussianModel(ℓ, (c_int, c_beta, c_bym2), A)

            res = inla(model, y; int_strategy=:grid)

            # --- Fixed effects: intercept + AFF slope --------------------
            fe = fixed_effects(model, res)
            @test length(fe) == 2
            α_R = _fixed_row(sf, "(Intercept)", "mean")
            β_R = _fixed_row(sf, "x", "mean")
            α_J = fe[1].mean
            β_J = fe[2].mean
            @test _rel(α_J, α_R) < FIXED_EFFECT_TOL
            @test _rel(β_J, β_R) < FIXED_EFFECT_TOL

            # --- Hyperparameters: τ (Precision) and φ (Phi) ---------------
            sh = fx["summary_hyperpar"]
            τ_R = _hyperpar_row(sh, "Precision for region", "mean")
            # Julia internal θ is [log τ, logit φ]. Approximate user-scale
            # τ at the mode (Gaussian posterior on log τ gives
            # E[τ] ≈ exp(θ̂₁ + σ²/2), but a point comparison suffices
            # for MVP).
            logτ̂_J = res.θ̂[1]
            τ̂_J = exp(logτ̂_J)
            @test _rel(τ̂_J, τ_R) < TAU_REL_TOL

            # φ is known to be weakly identified on moderate n — test
            # only finiteness/sanity of the Julia posterior.
            hp = hyperparameters(model, res)
            @test length(hp) == 2
            @test all(isfinite(r.mean) && r.sd > 0 for r in hp)

            # --- Marginal log-likelihood triangulation --------------------
            # R-INLA's mlik has two entries: [integration estimate,
            # Gaussian approximation]. Compare against the first (IS).
            mlik_R = Float64(fx["mlik"][1])
            mlik_J = log_marginal_likelihood(res)
            @test _rel(mlik_J, mlik_R) < MLIK_REL_TOL

            # --- Integrated θ marginal for τ (ADR-046) --------------------
            # dim(θ) = 2 → conditional-mode profile slice (fresh
            # warm-started Laplace fits along the τ axis). User-scale
            # moments vs the fixture's marginals.hyperpar density,
            # both reduced through the same trapezoid quadrature.
            if !haskey(fx, "marginals_hyperpar")
                @test_skip "fixture has no `marginals_hyperpar` — regenerate with the current R script"
            else
                mh_x, mh_y = marginal_grid(fx["marginals_hyperpar"]["Precision for region"])
                mom_R = oracle_pdf_moments(mh_x, mh_y)
                mom_J = precision_marginal_moments(
                    posterior_marginal_θ(res, 1; model=model, y=y))
                @test abs(mom_J.mean - mom_R.mean) / mom_R.mean < TAU_REL_TOL
                @test abs(mom_J.sd - mom_R.sd) / mom_R.sd < 0.25

                # φ marginal: weakly identified on Scotland — sanity only.
                mφ = posterior_marginal_θ(res, 2; model=model, y=y)
                @test all(isfinite, mφ.pdf)
                @test any(>(0), mφ.pdf)
            end
        end
    end
end
